//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvc_proje.Models.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class geziler
    {
        public int id { get; set; }
        public string ka { get; set; }
        public System.DateTime tarih { get; set; }
        public string sehir { get; set; }
        public string kategori { get; set; }
        public string baslik { get; set; }
        public string icerik { get; set; }
    }
}
