//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvc_proje.Models.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class kullanicilar
    {
        public string tc { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public string ka { get; set; }
        public string sifre { get; set; }
        public string email { get; set; }
        public string yas { get; set; }
        public bool kontrol { get; set; }
    }
}
