//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvc_proje.Models.entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mvcEntities : DbContext
    {
        public mvcEntities()
            : base("name=mvcEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<anasayfa> anasayfa { get; set; }
        public DbSet<bilgi> bilgi { get; set; }
        public DbSet<geziler> geziler { get; set; }
        public DbSet<iletisim> iletisim { get; set; }
        public DbSet<kullanicilar> kullanicilar { get; set; }
        public DbSet<resim> resim { get; set; }
    }
}
